apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fawkes

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - secret.yaml
  - ingress.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/name: friction-bot
      app.kubernetes.io/component: friction-logging
      app.kubernetes.io/part-of: fawkes-platform
