apiVersion: v1
kind: Service
metadata:
  name: friction-bot
  namespace: fawkes
  labels:
    app: friction-bot
    component: friction-logging
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: friction-bot
