apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fawkes

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: unleash
  app.kubernetes.io/part-of: fawkes-platform
  app.kubernetes.io/managed-by: argocd
