title = "Fawkes Gitleaks Configuration"

[allowlist]
description = "Allow placeholders used in educational materials"
regexes = [
  '''PLACEHOLDER_BASE64_VALUE''',
  '''CHANGEME_NOT_COMMITTED''',
  '''REDACTED_EXAMPLE'''
]
