apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smart-alerting
  namespace: fawkes
  labels:
    app: smart-alerting
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: smart-alerting
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
