apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app: external-secrets
    component: secret-store
    cloud: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2 # override via Kustomize patch per env
      auth:
        # Use IRSA: service account annotated with role allowing secrets access
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: platform
