apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources: []

labels:
  - pairs:
      app.kubernetes.io/part-of: fawkes
      app.kubernetes.io/component: policy-engine
    includeSelectors: false
