apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-java-app
  namespace: fawkes-samples
  labels:
    app: sample-java-app
    team: platform-team
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sample-java-app.fawkes.idp
      secretName: sample-java-app-tls
  rules:
    - host: sample-java-app.fawkes.idp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-java-app
                port:
                  number: 80
