apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - vault-auth-config.yaml
  - vault-policies.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: fawkes
      app.kubernetes.io/component: secrets-management
    includeSelectors: false
