apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-metrics
  namespace: fawkes-local
  labels:
    app: space-metrics
    component: devex
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: space-metrics.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: space-metrics
                port:
                  number: 8000
