apiVersion: v1
kind: Service
metadata:
  name: space-metrics
  namespace: fawkes-local
  labels:
    app: space-metrics
    component: devex
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: space-metrics
