apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fawkes

resources:
  - secretproviderclass.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: fawkes
      app.kubernetes.io/component: secrets-csi
    includeSelectors: false
