apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fawkes

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: discovery-metrics
  app.kubernetes.io/component: discovery
  app.kubernetes.io/part-of: fawkes
