apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - azure-disk-premium-storageclass.yaml
  - azure-disk-standard-storageclass.yaml
  - azure-file-storageclass.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: fawkes
      app.kubernetes.io/component: storage
    includeSelectors: false
