apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mandatory-security.yaml
  - mutation-policies.yaml
  - generation-policies.yaml
  - resource-constraints.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: fawkes
      app.kubernetes.io/component: kyverno-policies
    includeSelectors: false
