apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: default
  labels:
    app: ${{ values.name }}
    team: ${{ values.owner }}
spec:
  type: ClusterIP
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
