apiVersion: v1
kind: Service
metadata:
  name: feedback-bot
  namespace: fawkes
  labels:
    app: feedback-bot
    component: feedback
    platform: fawkes
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: feedback-bot
