apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-build-collector
  name: jenkins-build-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins-build-collector
    spec:
      containers:
      - env:
        - name: TEST_SCRIPT
          value: fixme
        - name: JENKINS_API_KEY
          value: 111af862ae55323068daf72f8786ce5b13
        - name: JENKINS_CRON
          value: 0 0/5 * * * *
        - name: JENKINS_MASTER
          value: http://ac31c3d2a5d3711e985de0ebf3e1312a-2067130682.us-east-1.elb.amazonaws.com:8080
        - name: JENKINS_NAME
          value: Jenkins (ns:pipeline - PROD)
        - name: JENKINS_SAVE_LOG
          value: "true"
        - name: JENKINS_USERNAME
          value: admin
        - name: MONGO_PORT
          value: tcp://db:27017
        image: paruff/hygieia-jenkins-build-collector:3.0.2.482
        name: jenkins-build-collector
        resources: {}
      restartPolicy: Always
status: {}
