apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: score-collector
  name: score-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: score-collector
    spec:
      containers:
      - env:
        - name: PROP_FILE
          value: application.properties
        - name: SCORE_CRON
          value: 0 0/5 * * * *
        - name: MONGODB_HOST
          value: db
        image: mssheldon/hygieia-score-collector
        name: score-collector
        resources: {}
      restartPolicy: Always
status: {}
